# This is a basic workflow to help you get started with Actions

name: Deploy Master

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "web-deploy"
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2.3.2

    - name: Use Node.js 14
      uses: actions/setup-node@v2-beta
      with:
        node-version: '14'
      
    - name: Build Project
      run: |
        npm install
        npm run generate

    - name: Sync Files
      uses: kevinpainchaud/simple-ftp-deploy-action@v1.2.1
      with:
        ftp_host: ${{ secrets.ftp_server }}
        ftp_username: ${{ secrets.ftp_username }}
        ftp_password: ${{ secrets.ftp_password }}
        local_source_dir: "dist"
        dist_target_dir: "public_html/creative/documentation"
        delete: "true"